### ISSUE TITLE
Reset game table if all players pass

### ISSUE THREAD

**Issue by Tom91011** [Tom91011/big-2-game#22]

**Comment by trullock** [comment]
this probably depends on a more richer feature of allowing multiple games per game. 
hint: we need some new Proper Nouns for these

**Comment by trullock** [comment]
We need a noun for this, whats is call when everyones passed, is that a Round (which is then over?) will go with that for now. @Tom91011 comment with a better noun if there is one

**Comment by trullock** [comment]
Also, whats the exact rule here? Is it really when all players pass, or when all but one pass (i.e. whoever played the high hand noone can beat)?

I think so, because their next act could be a better hand of the same class or anything else, theres no difference to gameplay, right?

So yeah, its when everyone else passes

**Comment by trullock** [comment]
This ticket has no meaning without #31, so I'll implement this at the same time
